version: 2.1

jobs:
  lint-and-typecheck:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt || true
            pip install -r requirements-dev.txt
      - run:
          name: Check code formatting with Black
          command: |
            . venv/bin/activate
            black --check .
      - run:
          name: Run type checking with Mypy
          command: |
            . venv/bin/activate
            mypy app/

workflows:
  lint_type_workflow:
    jobs:
      - lint-and-typecheck
