version: 2.1

jobs:
  lint-and-typecheck:
    docker:
      - image: cimg/python:3.11  # CircleCI image with Python preinstalled
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements-dev.txt

      # Check code formatting (Black)
      - run:
          name: Check code formatting with Black
          command: |
            . venv/bin/activate
            black --check .

      # Run static type checking (mypy)
      - run:
          name: Run mypy type checking
          command: |
            . venv/bin/activate
            mypy .
            
#Runs all unit tests in the /tests folder. Fails if any unit test fails.
  run-unit-tests:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies and run all unit tests
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            export SUPABASE_URL="https://fake.supabase.co"
            export SUPABASE_KEY="fake-key"
            pytest tests/ -v 

workflows:
  version: 2
  lint_and_typecheck_workflow:
    jobs:
      - lint-and-typecheck
      - run-unit-tests
