version: 2.1

jobs:
  lint-and-typecheck:
    docker:
      - image: cimg/python:3.11  # CircleCI image with Python preinstalled
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install black mypy

      # Check code formatting (Black)
      - run:
          name: Check code formatting with Black
          command: |
            . venv/bin/activate
            black --check .

      # Run static type checking (mypy)
      - run:
          name: Run mypy type checking
          command: |
            . venv/bin/activate
            mypy .

workflows:
  version: 2
  lint_and_typecheck_workflow:
    jobs:
      - lint-and-typecheck
